image: comp1531/automarking:latest

cache: 
  paths:
    - node_modules

stages:
  - checks

testing:
  stage: checks
  script: 
    - npm run test

typecheck:
  stage: checks
  script:
    - npm run tsc

linting:
  stage: checks
  script:
    - npm run lint

before_script:
  - npm install

tests:
  stage: checks
  only:
    - master
    - merge_requests
  script:
    - SERVER_LOG=$(mktemp)
    - npm run start >& $SERVER_LOG &
    - timeout 10s grep -q "⚡️ Server started on port" <(tail -f $SERVER_LOG) || (cat $SERVER_LOG && exit 1)
    - timeout -s SIGINT 180s npm run test || (cat $SERVER_LOG && exit 1)
    - kill -SIGINT %1
    - sleep 2
    - cat $SERVER_LOG

